apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-default
  namespace: pxdocs
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - docs.portworx.wk1.co
    secretName: ingress-pxdocs-default
  rules:
  - host: docs.portworx.wk1.co
    http:
      paths:
      - path: /
        backend:
          serviceName: docs-1-3
          servicePort: 80