sudo: required
dist: trusty
services:
  - docker
before_install:
  - sudo apt-get update -yq
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -yq docker-ce
script:
  - echo "Hello world"
notifications:
  email:
    recipients:
      - harsh@portworx.com
    on_success: change
    on_failure: always
